name: flustr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  #nostr: ^1.4.3
  nostr:
    git:
      url: https://github.com/uchijo/dart-nostr.git
      ref: feature/eoseSubscriptionId
  collection: ^1.18.0
  mockito: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
