name: nostrp2p
description: "A NostrP2P Client."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  #nostr: ^1.4.3
  nostr:
    git:
      url: https://github.com/uchijo/dart-nostr.git
      ref: feature/eoseSubscriptionId
  collection: ^1.18.0
  mockito: ^5.4.3
  bip340: ^0.2.0
  shared_preferences: ^2.2.2
  web: ^0.5.0
  web_socket_channel: 2.4.4
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  fetch_client: ^1.1.0-wasm
  cronet_http: ^1.1.1
  cupertino_http: ^1.3.0
  intl: ^0.19.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Bold.otf

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

